version: '3.8'

services:
  api:
    build: ./truck_signs_api
    container_name: "signs-for-trucks-django-backend-api"
    hostname: api
    volumes:
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    ports:
      - 8000
    env_file:
      - ./truck_signs_api/truck_signs_designs/settings/.env
    links:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_trucksigns_user
      - POSTGRES_PASSWORD=docker_supertrucksignsuser!
      - POSTGRES_DB=docker_trucksigns_db
  nginx:
    build: ./truck_signs_api/nginx
    volumes:
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    ports:
      - 80:80
    links:
      - api

  truck_signs_nextjs:
    build:
      context: ./truck_signs_frontend
      dockerfile: Dockerfile
    container_name: truck_signs_frontend-nextjs
    ports:
      - 3000:3000
    env_file: ./truck_signs_frontend/.env.local


volumes:
  postgres_data:
  django_static_volume:
  django_media_volume: