# Generated by Django 2.2.8 on 2021-06-29 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_in_hex', models.CharField(default='#000000', max_length=256, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'only valid hex color code is accepted')])),
                ('color_nickname', models.CharField(default='add nickname', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_type_of_product', models.CharField(default='Truck Logo', max_length=256, unique=True)),
                ('single_image', models.ImageField(upload_to='uploads/products_types/')),
                ('base_price', models.FloatField(default=0.0)),
                ('is_company_name_enable', models.BooleanField(default=False)),
                ('company_name_price', models.FloatField(default=0.0)),
                ('is_dot_number_enable', models.BooleanField(default=False)),
                ('dot_number_price', models.FloatField(default=0.0)),
                ('is_mc_number_enable', models.BooleanField(default=False)),
                ('mc_number_price', models.FloatField(default=0.0)),
                ('is_origin_enable', models.BooleanField(default=False)),
                ('origin_price', models.FloatField(default=0.0)),
                ('is_vim_number_enable', models.BooleanField(default=False)),
                ('vim_number_price', models.FloatField(default=0.0)),
                ('is_truck_number_enable', models.BooleanField(default=False)),
                ('truck_number_price', models.FloatField(default=0.0)),
                ('is_color_enable', models.BooleanField(default=False)),
                ('color_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_image', models.ImageField(upload_to='uploads/products/single_images')),
                ('order_image', models.ImageField(upload_to='uploads/products/order_images')),
                ('is_single_image_for_show', models.BooleanField(default=True)),
                ('type_of_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_made', models.DateField(auto_now_add=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('user_email', models.CharField(max_length=256)),
                ('user_first_name', models.CharField(max_length=256)),
                ('user_last_name', models.CharField(max_length=256)),
                ('send_email_proof', models.BooleanField(default=False)),
                ('address1', models.CharField(default='Address line 1', max_length=1024)),
                ('address2', models.CharField(blank=True, default='Address line 2', max_length=1024, null=True)),
                ('city', models.CharField(default='Miami', max_length=60)),
                ('state', models.CharField(default='Florida', max_length=30)),
                ('zipcode', models.CharField(default='33165', max_length=5)),
                ('country', models.CharField(default='USA', max_length=50)),
                ('order_is_complete', models.BooleanField(default=False)),
                ('product_type', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('dot_number', models.CharField(blank=True, max_length=256)),
                ('mc_number', models.CharField(blank=True, max_length=256)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('vin_number', models.CharField(blank=True, max_length=256)),
                ('truck_number', models.CharField(blank=True, max_length=256)),
                ('comments', models.CharField(blank=True, max_length=256)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Product')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ProductColor')),
            ],
        ),
    ]
