# Generated by Django 2.2.8 on 2021-06-29 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='uploads/categories/')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LetteringItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'lettering item categories',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=256)),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('base_price', models.FloatField(default=0.0)),
                ('max_amount_of_lettering_items', models.FloatField(default=-1)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('only_on_default_color', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_in_hex', models.CharField(default='#000000', max_length=256, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'only valid hex color code is accepted')])),
                ('color_nickname', models.CharField(default='add nickname', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Product')),
                ('product_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ProductColor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('user_email', models.CharField(max_length=256)),
                ('user_first_name', models.CharField(max_length=256)),
                ('user_last_name', models.CharField(max_length=256)),
                ('address1', models.CharField(default='Address line 1', max_length=1024)),
                ('address2', models.CharField(blank=True, default='Address line 2', max_length=1024, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Payment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ProductVariation')),
            ],
        ),
        migrations.CreateModel(
            name='LetteringItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letteting', models.CharField(max_length=256)),
                ('lettering_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.LetteringItemCategory')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ProductVariation')),
            ],
        ),
    ]
