# Generated by Django 2.2.8 on 2021-06-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letteringitemvariation',
            old_name='letteting',
            new_name='lettering',
        ),
    ]
