# Generated by Django 2.2.8 on 2021-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_truckitem_is_single_image_for_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('singleImage', models.ImageField(upload_to='uploads/other_products/singleImages')),
                ('multiImage', models.ImageField(upload_to='uploads/other_products/multiImages')),
                ('is_single_image_for_show', models.BooleanField(default=False)),
            ],
        ),
    ]
