# Generated by Django 2.2.8 on 2021-04-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_otherproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherproduct',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='truckitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
