# Generated by Django 2.2.8 on 2021-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210520_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name_of_type_of_product',
            field=models.CharField(default='Truck Logo', max_length=256, unique=True),
        ),
    ]
