# Generated by Django 2.2.8 on 2021-07-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_product',
            field=models.IntegerField(default=1),
        ),
    ]
