# Generated by Django 2.2.8 on 2021-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210404_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_made', models.DateField(auto_now_add=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('user', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('send_email_proof', models.BooleanField(default=False)),
                ('order_is_complete', models.BooleanField(default=False)),
                ('has_truck_item', models.BooleanField(default=False)),
                ('truck_color', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('dot_number', models.CharField(blank=True, max_length=256)),
                ('mc_number', models.CharField(blank=True, max_length=256)),
                ('origin', models.CharField(blank=True, max_length=256)),
                ('vin_number', models.CharField(blank=True, max_length=256)),
                ('has_truck_number', models.BooleanField(default=False)),
                ('truck_number', models.CharField(blank=True, max_length=256)),
                ('has_fire_Extinguisher', models.BooleanField(default=False)),
                ('comments', models.TextField()),
            ],
        ),
    ]
