# Generated by Django 2.2.8 on 2021-04-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.TruckItem'),
        ),
    ]
