# Generated by Django 2.2.8 on 2021-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210520_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='single_image',
            field=models.ImageField(upload_to='uploads/products_types/'),
        ),
    ]
