# Generated by Django 2.2.8 on 2021-07-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210721_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_amount_of_lettering_items',
        ),
        migrations.AddField(
            model_name='category',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='category',
            name='max_amount_of_lettering_items',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
