# Generated by Django 2.2.8 on 2021-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_orderitem_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherproduct',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='truckitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
