# Generated by Django 2.2.8 on 2021-04-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210404_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckitem',
            name='nickname',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
