# Generated by Django 2.2.8 on 2021-05-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210520_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
