# Generated by Django 2.2.8 on 2021-07-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210722_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='category',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
