# Generated by Django 2.2.8 on 2021-04-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210428_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='address1',
            field=models.CharField(default='Address line 1', max_length=1024),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='address2',
            field=models.CharField(blank=True, default='Address line 2', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='city',
            field=models.CharField(default='Miami', max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='country',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(default='Florida', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zipcode',
            field=models.CharField(default='33165', max_length=5),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
