# Generated by Django 2.2.8 on 2021-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210722_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='uploads/products_detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/products/'),
        ),
    ]
