# Generated by Django 2.2.8 on 2021-07-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210722_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ProductColor'),
        ),
    ]
