# Generated by Django 2.2.8 on 2021-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210428_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsToShowInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, unique=True)),
                ('type_of_product', models.CharField(max_length=256, unique=True)),
                ('singleImage', models.ImageField(upload_to='uploads/products/singleImages')),
                ('multiImage', models.ImageField(upload_to='uploads/products/multiImages')),
                ('is_single_image_for_show', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CartToShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=256)),
                ('total_cost', models.FloatField(default=0.0)),
                ('items', models.ManyToManyField(null=True, to='backend.ItemsToShowInCart')),
            ],
        ),
    ]
