# Generated by Django 2.2.8 on 2021-04-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_carttoshow_itemstoshowincart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsToShowInCart',
        ),
        migrations.DeleteModel(
            name='OtherProduct',
        ),
        migrations.AlterField(
            model_name='carttoshow',
            name='items',
            field=models.ManyToManyField(null=True, to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(default='Truck Logo', max_length=256),
        ),
        migrations.DeleteModel(
            name='TruckItem',
        ),
    ]
