# Generated by Django 2.2.8 on 2021-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210429_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='has_side_only_letters',
            field=models.BooleanField(default=False),
        ),
    ]
