# Generated by Django 2.2.8 on 2021-07-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210724_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteringitemvariation',
            name='lettering_item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.LetteringItemCategory'),
        ),
    ]
